### ISSUE TITLE
Fix bsb-native to work with npm5

### ISSUE THREAD

**Issue by bsansouci** [bsansouci/bsb-native#11]
This has been a very annoying one for everyone. About 80% of problems lately have been when someone tries to install using npm5. It always takes me a while to diagnose.

**Comment by ox** [comment]
I was running into this issue and tried to debug it. A workaround that I found was cloning the repo and installing it as a symbolic dep:

```
npm install -D bs-platform@file:../bsb-native
```

After that everything worked well.

I have saved logs of both compilations in [this gist](https://gist.github.com/ox/8eeef0cb5f0ed2e154a4e0ca9da3eadc). Hopefully it might shed some light on what's different for anyone digging into this issue.

**Comment by Schmavery** [comment]
Solved by installing bsansouci/bsb-native#2.1.1
@bsansouci

**Comment by bsansouci** [comment]
Yup! Closing.
