### ISSUE TITLE
Create a default package for --init for native

### ISSUE THREAD

**Issue by bsansouci** [bsansouci/bsb-native#20]
The title says it all.

`--init` supports generate a default package. Currently we point people to https://github.com/bsansouci/bsb-native-example but we should also have a way to generate this from `--init`

**Comment by Lokeh** [comment]
Is there a good way to have bsb-native installed globally (so I can use the -init parameter), without clobbering mainline bsb?

**Comment by bsansouci** [comment]
@Lokeh hey! I’m not sure what you’re asking. What do you mean clobbering?
You can always do `npm install -g bsansouci/bsb-native#2.1.1` to install globally.

**Comment by Lokeh** [comment]
If I already have bsb installed for working with JS, I may not want to install bsb-native over it. Bsb-native will overwrite my original bsb installation if I install it globally, right?

**Comment by bsansouci** [comment]
Yeah, you can simply install bsb-native locally :) (bsb as well can be installed locally).
Then you can call it directly `./node_modules/.bin/bsb` or through a npm script.
