### ISSUE TITLE
Allow naming of executables

### ISSUE THREAD

**Issue by IwanKaramazow** [bsansouci/bsb-native#38]
the following entry
```
{
    "backend": "native",
    "main-module": "Utf8_test"
}
```
results in a `utf8_test.native` executable.

When building an executable for a windows system, it would be convenient if we could give the executable another name & extension. 
Example: `utf8_test.native` would become `runtest.exe`

**Comment by bsansouci** [comment]
Ok I can add a field “name”. 
What’s your current usecase

**Comment by IwanKaramazow** [comment]
I've got two use cases:
1) Windows: there's a restriction which requires executables to be named as `.exe`.
2) (More of a question) If I'm developing a medical app called "doctor", and the main entry-point is a module called `Startup`. Am I forced to rename the `Startup`-module to `Doctor` to have a nice name on the executable? Post-hoc renaming with a shell script doesn't feel like the best workflow in the world.
