### ISSUE TITLE
ocaml compiler build failure

### ISSUE THREAD

**Issue by bobpoekert** [bsansouci/bsb-native#45]
If you run `npm install -g bsb-native` on a fresh ubuntu 17.10 install (after running `apt-get install npm`) you get the following error:

```
Build a local version of OCaml compiler, it may take a couple of minutes
File "_none_", line 1:
Error: Files super_packed.cmx and typing/typetexp.cmx
       make inconsistent assumptions over implementation Typetexp
make[2]: *** [compilerlibs/ocamlcommon.cmxa] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [opt.opt] Error 2
make: *** [world.opt] Error 2
```

**Comment by bsansouci** [comment]
Mmmh master might be a broken. Can you try the release: `npm install bsansouci/bs-platform#2.1.1`?

**Comment by bobpoekert** [comment]
Yes that worked

**Comment by bsansouci** [comment]
Ok awesome. Sorry about that, master will be a bit less stable than the release so I’d recommend using the releases. A new one’s coming up soon :)
