### ISSUE TITLE
Allow passing flags to ocaml

### ISSUE THREAD

**Issue by anmonteiro** [bsansouci/bsb-native#7]
In particular I'm getting the following error:

> ocamlfind: Error from packagethreads': Missing -thread or -vmthread switch

I think in this case I would just need to be able to pass the `-thread` flag and it would compile cleanly.

**Comment by bsansouci** [comment]
You made a patch but there was one thing we forgot, we didn't pass the warnings flag to bsb_helper (the linker / packer). Fixed now.
