### ISSUE TITLE
Should ignore modules that are not used

### ISSUE THREAD

**Issue by WhoAteDaCake** [bsansouci/bsb-native#70]
Currently if i have a library that has optional functionality that depends on JavaScript you will not be able to build native code.

For example:
When using [wonka](https://github.com/kitten/wonka) which provides JavaScript event handling, I won't be able to build code that doesn't even use JavaScript bindings:
```ocaml
let example = [1, 2, 3, 4, 5, 6];

/* Curently forced to inject wonka as bs-native can't be compiled properly */
Wonka.fromList(example)
|> Wonka.filter(x => x mod 2 === 0)
|> Wonka.map(x => x * 2)
|> Wonka.forEach(x => print_endline(string_of_int(x)));
```

Will throw:
```
  27 │    */
  28 │ let fromDomEvent:
  29 │   (Dom.element, string, signalT(Dom.event) => unit) => unit;
  30 │ 
  31 │ /* Accepts a period in milliseconds and creates a listenable source
  
  The module or file Dom can't be found.
```

**Comment by bsansouci** [comment]
Thanks for reporting this issue. There's a way to do this currently, by `include`ing different implementation modules hidden under a `#if BSB_BACKEND = "native"` check.
See [reprocessing's hot reloading implementation](https://github.com/Schmavery/reprocessing/blob/62b17807dfdee075aa5c9230973c7307b02de895/src/Reprocessing_Hotreload.ml).

I'd love to find a better way to do this.

**Comment by WhoAteDaCake** [comment]
Ahh I see, thank you for the response
